name: exploit-poker
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Santiago Weight
github: santiweight/Exploit
license: BSD3
description: Please see the README on GitHub at <https://github.com/githubuser/Exploit#readme>
copyright: 2019 Santiago Weight
maintainer: santiago.weight@gmail.com

executables:
  simple:
    main: app/Simple.hs
    ghc-options:
    - -Wall
    dependencies:
    - poker-base
    - exploit-poker

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  build-tools:
    - alex
    - happy

tests:
  exploit-poker-test:
    source-dirs:
    - test
    main: Driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - exploit-poker
    - tasty
    - tasty-hspec
    - tasty-hunit
    - tasty-discover

dependencies:
- poker-base
- aeson
- array
- async
- base
- bytestring
- comonad
- containers
- data-default
- deriving-compat
- directory
- filepath
- free
- generic-arbitrary
- generic-data
- lens
- megaparsec
- monad-loops
- mtl
- optparse-applicative
- polysemy
- polysemy-plugin
- prettyprinter
- QuickCheck
- recursion-schemes
- scientific
- singletons
- sort
- string-conversions
- text
- time
- transformers
default-extensions:
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- GADTs
- LambdaCase
- LiberalTypeSynonyms
- OverloadedStrings
- PartialTypeSignatures
- PatternSynonyms
- PackageImports
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- TypeFamilies
- UnicodeSyntax
- TemplateHaskell