library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
tests:
  Exploit-test:
    source-dirs:
    - test
    - src
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- containers
- polysemy
- base
- uniplate
- singletons
- deriving-compat
- comonad
- recursion-schemes
- free
- free
- aeson
- async
- base >=4.7 && <5
- bytestring
- containers
- data-default
- dates
- directory
- do-notation
- either
- errors
- error-util
- gi-gdk
- gi-gio
- gi-gtk
- haskell-gi
- haskell-gi-base
- HUnit
- indexed-extras
- indexed
- lens
- megaparsec >=8.0.0
- MissingH
- monad-loops
- mtl
- parsec
- parser-combinators
- polysemy-plugin
- pretty-simple
- random
- regex-pcre
- regex-posix
- random-shuffle
- scientific
- Stream
- sort
- tasty
- tasty-hunit
- tasty-hspec
- text
- text-format-simple
- timeit
- transformers
- unordered-containers
- unbounded-delays
- utility-ht
- vector
default-extensions:
  - TypeApplications
  - ScopedTypeVariables
  - TypeOperators
  - RankNTypes
  - PartialTypeSignatures
  - FlexibleContexts
  - ConstraintKinds
  - EmptyCase
  - StandaloneDeriving
  - GADTs
  - TypeFamilies
  - UnicodeSyntax
  - PatternSynonyms
  - LiberalTypeSynonyms
  - PolyKinds
  - NoMonomorphismRestriction
  - AllowAmbiguousTypes
  - DataKinds
  - LambdaCase
  - TemplateHaskell
name: Exploit
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/Exploit
license: BSD3
executables:
  Exploit-exe:
    source-dirs:
    - src
    - app
    main: GUI.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
description: Please see the README on GitHub at <https://github.com/githubuser/Exploit#readme>
