author: Santiago Weight
github: santiweight/Exploit
license: BSD3
executables:
  simple:
    main: app/Simple.hs
    ghc-options:
    - -Wall
    dependencies:
    - Exploit
  backend:
    main: app/Backend.hs
    ghc-options:
    - -Wall
    dependencies:
    - Exploit
  gui:
    main: app/GUI.hs
    ghc-options:
    - -Wall
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded
    dependencies:
    - Exploit
  imp:
    main: app/Imperative.hs
    ghc-options:
    - -Wall
    - -rtsopts
    - -with-rtsopts=-N
    - -threaded
    - -O2
    dependencies:
    - Exploit
description: Please see the README on GitHub at <https://github.com/githubuser/Exploit#readme>
library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
tests:
  Exploit-test:
    source-dirs:
    - test
    main: Driver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fplugin=Polysemy.Plugin
    dependencies:
    - Exploit
copyright: 2019 Santiago Weight
maintainer: santiago.weight@gmail.com
dependencies:
- haskell-gi-base
- gi-gobject
- esqueleto
- serialise
- deepseq
- monad-logger
- persistent
- persistent-template
- persistent-postgresql
- attoparsec
- base-compat
- string-conversions
- servant-lucid
- lucid
- servant
- servant-server
- wai
- warp
- http-media
- time
- optparse-applicative
- base
- syb
- containers
- polysemy
- base
- uniplate
- singletons
- deriving-compat
- comonad
- array
- recursion-schemes
- free
- aeson
- async
- extra
- base >=4.7 && <5
- bytestring
- containers
- data-default
- dates
- directory
- do-notation
- either
- errors
- filepath
- generic-arbitrary
- generic-data
- gi-gdk
- gi-gio
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- haskell-gi
- haskell-gi-base
- tasty-discover
- HUnit
- indexed-extras
- indexed
- lens
- megaparsec >=8.0.0
- MissingH
- monad-loops
- mtl
- polysemy-plugin
- prettyprinter
- QuickCheck
- quickcheck-assertions
- random
- regex-pcre
- regex-posix
- resourcet
- random-shuffle
- scientific
- Stream
- sort
- tasty
- tasty-hunit
- tasty-hspec
- tasty-quickcheck
- text
- text-format-simple
- timeit
- transformers
- uniplate
- unordered-containers
- unbounded-delays
- utility-ht
- vector
default-extensions:
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- EmptyCase
- FlexibleContexts
- GADTs
- LambdaCase
- LiberalTypeSynonyms
- PartialTypeSignatures
- PatternSynonyms
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators
- TypeFamilies
- UnicodeSyntax
- TemplateHaskell
name: Exploit
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
